name: CI
on:
  push:
    branches: '**'
  pull_request:
    branches: 'master'

jobs:
  windows:
    runs-on: windows-2016
    env:
      DEPS_BUILD_DIR: "C:/projects/nvim-deps"
      DEPS_PREFIX: "C:/projects/nvim-deps/usr"

    strategy:
      fail-fast: false
      matrix:
        config: [ MINGW_64-gcov, MINGW_32, MSVC_64, MSVC_32 ]
    name: windows (${{ matrix.config }})
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: C:\projects\nvim-deps
          key: ${{ matrix.config }}-${{ hashFiles('third-party\**') }}

      - name: Run CI
        run: powershell ci\build.ps1
        env:
          CONFIGURATION: ${{ matrix.config }}
